name: Build and Deploy APK and AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [apk, aab]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --force

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./android/gradlew

      - name: Build Android APK
        if: matrix.target == 'apk'
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Build Android AAB
        if: matrix.target == 'aab'
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload APK
        if: matrix.target == 'apk'
        uses: actions/upload-artifact@v2
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB
        if: matrix.target == 'aab'
        uses: actions/upload-artifact@v2
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
